set(VCPKG_TARGET_ARCHITECTURE x86)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

# ReactWindows OpenSSL
set(VCPKG_PLATFORM_TOOLSET v141)
#set(VCPKG_BUILD_TYPE debug)
#set(VCPKG_BUILD_TYPE release)